[package]
name = "linear_vesting_escrow"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v5.0.0-rc.1", directory = "noir-projects/aztec-nr/aztec" }
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.10.0" }
escrow_standard = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "prerelease-15b49c2", directory = "src/escrow_contract" }
token = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "prerelease-15b49c2", directory = "src/token_contract" }
nft = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "prerelease-15b49c2", directory = "src/nft_contract" }
