name: PR Checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  benchmark:
    uses: defi-wonderland/aztec-benchmark/.github/workflows/pr-benchmark.yml@prerelease-022ee63
    permissions:
      contents: read
      pull-requests: write
      issues: write
      actions: read
    secrets: inherit
