name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: defi-wonderland/aztec-ci-actions/.github/workflows/run-tests.yml@v0
